spring:
  application:
    name: Stock-Prediction-Chatbot
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:mysql://capston-db.chpfefcly6jj.ap-northeast-2.rds.amazonaws.com
    username: admin
    password: yeo3420211!
    driver-class-name: com.mysql.cj.jdbc.Driver
